#!/bin/bash

# This script sets up the cron jobs for the stockv2 project.
# It dynamically determines the project's absolute path to ensure the cron jobs run correctly for any user.

# --- Get the absolute path of the project directory (where this script is located) ---
# The script is in script/, so we go up one level.
PROJECT_DIR=$(cd "$(dirname "$0")/.." && pwd)

# --- Define the log file path ---
LOG_FILE="${PROJECT_DIR}/logs/cron.log"

# --- Create the log file and set permissions if it doesn't exist ---
touch "${LOG_FILE}"
chmod 664 "${LOG_FILE}"

# --- Define the crontab content ---
# We use a temporary file to build the crontab content.
CRON_FILE_CONTENT=$(mktemp)

# Note: We escape backslashes and percent signs for the echo command.
cat > "${CRON_FILE_CONTENT}" <<EOF
# Cron jobs for the stockv2 project
# Generated by setup_cron.sh on $(date)

# 毎日、日本時間の午前7時にデータ更新と全銘柄の予測を実行する (22:00 UTC)
0 22 * * * /usr/bin/bash -c 'cd ${PROJECT_DIR} && make update-data && make predict-all' >> ${LOG_FILE} 2>&1

# 毎週日曜日の日本時間午前8時に、保留中の通知をすべて送信する (23:00 UTC on Saturday)
0 23 * * 6 /usr/bin/bash -c 'cd ${PROJECT_DIR} && make send-notifications' >> ${LOG_FILE} 2>&1
EOF

# --- Install the new crontab ---
crontab "${CRON_FILE_CONTENT}"

# --- Clean up the temporary file ---
rm "${CRON_FILE_CONTENT}"

# --- Provide feedback to the user ---
echo "Crontab has been successfully updated."
echo "Log output will be written to: ${LOG_FILE}"
echo "You can check the installed cron jobs by running: crontab -l"
